export const bibleData = {
    'new testament': {
        Matthew: { chapters: 1, verses: 1 },
        Mark: { chapters: 1, verses: 1 },
        Luke: { chapters: 1, verses: 1 },
        John: { chapters: 1, verses: 1 },
        Acts: { chapters: 1, verses: 1 },
        Romans: { chapters: 1, verses: 1 },
        '1 Corinthians': { chapters: 1, verses: 1 },
        '2 Corinthians': { chapters: 1, verses: 1 },
        Galatians: { chapters: 1, verses: 1 },
        Ephesians: { chapters: 1, verses: 1 },
        Philippians: { chapters: 1, verses: 1 },
        Colossians: { chapters: 1, verses: 1 },
        '1 Thessalonians': { chapters: 1, verses: 1 },
        '2 Thessalonians': { chapters: 1, verses: 1 },
        '1 Timothy': { chapters: 1, verses: 1 },
        '2 Timothy': { chapters: 1, verses: 1 },
        Titus: { chapters: 1, verses: 1 },
        Philemon: { chapters: 1, verses: 1 },
        Hebrews: { chapters: 1, verses: 1 },
        James: { chapters: 1, verses: 1 },
        '1 Peter': { chapters: 1, verses: 1 },
        '2 Peter': { chapters: 1, verses: 1 },
        '1 John': { chapters: 1, verses: 1 },
        '2 John': { chapters: 1, verses: 1 },
        '3 John': { chapters: 1, verses: 1 },
        Jude: { chapters: 1, verses: 1 },
        Revelation: { chapters: 1, verses: 1 },
    },
    'old testament': {
        Genesis: { chapters: 1, verses: 1 },
        Exodus: { chapters: 1, verses: 1 },
        Leviticus: { chapters: 1, verses: 1 },
        Numbers: { chapters: 1, verses: 1 },
        Deuteronomy: { chapters: 1, verses: 1 },
        Joshua: { chapters: 1, verses: 1 },
        Judges: { chapters: 1, verses: 1 },
        Ruth: { chapters: 1, verses: 1 },
        '1 Samuel': { chapters: 1, verses: 1 },
        '2 Samuel': { chapters: 1, verses: 1 },
        '1 Kings': { chapters: 1, verses: 1 },
        '2 Kings': { chapters: 1, verses: 1 },
        '1 Chronicles': { chapters: 1, verses: 1 },
        '2 Chronicles': { chapters: 1, verses: 1 },
        Ezra: { chapters: 1, verses: 1 },
        Nehemiah: { chapters: 1, verses: 1 },
        Tobit: { chapters: 1, verses: 1 },
        Judith: { chapters: 1, verses: 1 },
        Esther: { chapters: 1, verses: 1 },
        '1 Maccabees': { chapters: 1, verses: 1 },
        '2 Maccabees': { chapters: 1, verses: 1 },
        Job: { chapters: 1, verses: 1 },
        Psalms: { chapters: 1, verses: 1 },
        Proverbs: { chapters: 1, verses: 1 },
        Ecclesiastes: { chapters: 1, verses: 1 },
        'Song of Songs': { chapters: 1, verses: 1 },
        Wisdom: { chapters: 1, verses: 1 },
        Sirach: { chapters: 1, verses: 1 },
        Isaiah: { chapters: 1, verses: 1 },
        Jeremiah: { chapters: 1, verses: 1 },
        Lamentations: { chapters: 1, verses: 1 },
        Baruch: { chapters: 1, verses: 1 },
        Ezekiel: { chapters: 1, verses: 1 },
        Daniel: { chapters: 1, verses: 1 },
        Hosea: { chapters: 1, verses: 1 },
        Joel: { chapters: 1, verses: 1 },
        Amos: { chapters: 1, verses: 1 },
        Obadiah: { chapters: 1, verses: 1 },
        Jonah: { chapters: 1, verses: 1 },
        Micah: { chapters: 1, verses: 1 },
        Nahum: { chapters: 1, verses: 1 },
        Habakkuk: { chapters: 1, verses: 1 },
        Zephaniah: { chapters: 1, verses: 1 },
        Haggai: { chapters: 1, verses: 1 },
        Zechariah: { chapters: 1, verses: 1 },
        Malachi: { chapters: 1, verses: 1 },
    }
}